name: Flutter Build (Android & iOS)

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Môi trường muốn Build (android, ios, cả hai)'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - android
          - ios

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    if: ${{ github.event.inputs.build_target == 'both' || github.event.inputs.build_target == 'android' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 'any'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    if: ${{ github.event.inputs.build_target == 'both' || github.event.inputs.build_target == 'ios' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 'any'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      # Lưu ý: Lệnh này chỉ build ra file .app (chưa sign).
      # Để build ra .ipa đẩy lên App Store, bạn cần cấu hình Certificate và Provisioning Profile trên Apple Developer.
      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios/iphoneos/Runner.app
